### ISSUE TITLE
Correction in comment

### ISSUE THREAD

**Issue by Wajihulhassan** [daveti/usbfilter#1]
At line https://github.com/daveti/usbfilter/blob/master/teensyduino/usbfilter-4ifs.ino#L2 it should be 5 interfaces rather than 4 interfaces as in the code below you have two serial ports. Also, the paper mentioned two serial ports in evaluation section

**Comment by daveti** [comment]
Ugh.... yes, thanks for catching that. I remember having a hard time of making one of the serial ports actually work. Anyway, it is 5 interfaces in total.
